export const langText = {
  en: {
    explore: 'Explore',
    tagline: 'Start your journey now!',
    noCountry: 'No such country founds',
    search: 'Country or capital',
    labelComment: 'Enter your comment:',
    labelRating: 'Place rating',
    submit: 'Submit',
    creator: [
      'Created by',
      'Oleg Kuzmin',
      'Anastasia Tiapkina',
      'Rinat Nassibullin',
      'Vlad Kryvokoniev',
    ],
  },
  ru: {
    explore: 'Посетить',
    tagline: 'Начни путешествие прямо сейчас!',
    noCountry: 'Нет похожей страны в нашем списке',
    search: 'Страна или столица',
    labelComment: 'Введите ваш коментарий:',
    labelRating: 'Рейтинг места',
    submit: 'Отправить',
    creator: [
      'Создатели проекта:',
      'Олег Кузьмин',
      'Анастасия Тяпкина',
      'Ринат Насибуллин',
      'Влад Кривоконев',
    ],
  },
  de: {
    explore: 'Erkunden',
    tagline: 'Beginnen Sie jetzt Ihre Reise!',
    noCountry: 'Keine solchen Länder gefunden',
    search: 'Land oder Hauptstadt',
    labelComment: 'Geben Sie Ihre Ihren Kommentar ein:',
    labelRating: 'Platzbewertung',
    submit: 'Einreichen',
    creator: [
      'Projektersteller:',
      'Oleg Kuzmin',
      'Anastasia Tiapkina',
      'Rinat Nassibullin',
      'Vlad Kryvokoniev',
    ],
  },
};
